management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics,prometheus' # 👈 確保這四個都開
  metrics:
    tags:
      application: ${spring.application.name} # 👈 這行極度重要！它會自動抓該服務在 Nacos 的名稱
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C

logging:
  loki:
    url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
    enabled: ${LOKI_ENABLED:true}
